### PR TITLE
a few minor grammar and typo fixes

### PR DESCRIPTION
**Pull request by williamdemeo**

### CODE REVIEW

**Comment by williamdemeo** [comment]
It looks like my most recent suggested changes were not pulled.  I'll take that to mean you'd rather not be bothered with pull requests that merely fix typos and/or improve grammar, and I'll stop suggesting such improvements.

**Comment by avigad** [comment]
A couple of days ago I did indeed incorporate your latest changes: https://github.com/leanprover/theorem_proving_in_lean/commit/d8d97b9d7808536da218fbbadc01c748f5f2efa3. I see I missed one "H" and the "typs" correction -- my apologies. I will fix them now. 

The corrections are indeed helpful. It would help if the commits were rebased on top of the current master and if you used the commit conventions (which are essentially a variant of these: https://github.com/leanprover/lean/blob/master/doc/commit_convention.md; you can just say e.g. "fix(03): fix typos"). Otherwise, your commit record doesn't match ours, and I have to exercise my lousy git-fu to incorporate the changes.

**Comment by avigad** [comment]
Actually, as far as I can tell, the only correction I missed was an H -> h. Are there others?

**Comment by williamdemeo** [comment]
Thanks for the advice on commit conventions.  That's very helpful.  I will try to use those conventions in the future, and I'll also be sure to rebase with the upstream repo before submitting pull requests in the future.

As for changes from my last pull request that were not incorporated, there are only two and both are insignificant, so I don't think it's worth wasting your time with another pull request. 

I'll rebase my fork to be in sync with the upstream master before any future pull requests.  (Actually, I did try to do that before my most recent pull request, but I guess for some reason I wasn't entirely successful.)

The two minor suggestions I have (which didn't make it into the last merge) are the following:

1. include instructions for typing the negation symbol (with `\not`).  This might help folks who are accustomed to LaTeX commands (such as `\neg`).

2. should you change "The classical axioms also gives you..." to "The classical axioms also give you..."?
  Now I'm nit-picking.  Feel free to ignore these suggestions, of course.

**Comment by avigad** [comment]
Both of those have already been incorporated:

https://github.com/leanprover/theorem_proving_in_lean/blob/master/03_Propositions_and_Proofs.org

I just checked both the html and the pdf online again to make sure.

**Comment by williamdemeo** [comment]
Sorry, I must not have fetched from upstream recently, and I suppose that would explain why my fork appeared to be some number of commits ahead of your master.  Sorry to waste your time.

**Comment by avigad** [comment]
No problem! Again, we appreciate the help.

**Pull request closed without merging**
